name: Build and Test

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Xcode
      run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

    - name: Install CMake and Ninja
      run: brew install cmake ninja

    - name: Build the Project
      run: make

    - name: Run
      run: make run

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install CMake, Ninja and Clang
      run: |
        sudo apt-get update
        sudo apt-get install cmake ninja-build
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 15  # Install Clang 15
        sudo apt-get install -y clang-15 lldb-15 lld-15

    - name: Set Environment Variables
      run: |
        echo "CC=/usr/bin/clang-15" >> $GITHUB_ENV
        echo "CXX=/usr/bin/clang++-15" >> $GITHUB_ENV

    - name: Build the Project
      run: make

    - name: Run
      run: make run
